/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as BenchmarksRouteImport } from './routes/benchmarks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScanNewRouteImport } from './routes/scan.new'
import { Route as ScanIdRouteImport } from './routes/scan.$id'
import { Route as BenchmarksRunIdRouteImport } from './routes/benchmarks.$runId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksRoute = BenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanNewRoute = ScanNewRouteImport.update({
  id: '/scan/new',
  path: '/scan/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanIdRoute = ScanIdRouteImport.update({
  id: '/scan/$id',
  path: '/scan/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksRunIdRoute = BenchmarksRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => BenchmarksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/benchmarks': typeof BenchmarksRouteWithChildren
  '/history': typeof HistoryRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/benchmarks/$runId': typeof BenchmarksRunIdRoute
  '/scan/$id': typeof ScanIdRoute
  '/scan/new': typeof ScanNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/benchmarks': typeof BenchmarksRouteWithChildren
  '/history': typeof HistoryRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/benchmarks/$runId': typeof BenchmarksRunIdRoute
  '/scan/$id': typeof ScanIdRoute
  '/scan/new': typeof ScanNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/benchmarks': typeof BenchmarksRouteWithChildren
  '/history': typeof HistoryRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/benchmarks/$runId': typeof BenchmarksRunIdRoute
  '/scan/$id': typeof ScanIdRoute
  '/scan/new': typeof ScanNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/benchmarks'
    | '/history'
    | '/reports'
    | '/settings'
    | '/benchmarks/$runId'
    | '/scan/$id'
    | '/scan/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/benchmarks'
    | '/history'
    | '/reports'
    | '/settings'
    | '/benchmarks/$runId'
    | '/scan/$id'
    | '/scan/new'
  id:
    | '__root__'
    | '/'
    | '/benchmarks'
    | '/history'
    | '/reports'
    | '/settings'
    | '/benchmarks/$runId'
    | '/scan/$id'
    | '/scan/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenchmarksRoute: typeof BenchmarksRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  ScanIdRoute: typeof ScanIdRoute
  ScanNewRoute: typeof ScanNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks': {
      id: '/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof BenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/new': {
      id: '/scan/new'
      path: '/scan/new'
      fullPath: '/scan/new'
      preLoaderRoute: typeof ScanNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/$id': {
      id: '/scan/$id'
      path: '/scan/$id'
      fullPath: '/scan/$id'
      preLoaderRoute: typeof ScanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks/$runId': {
      id: '/benchmarks/$runId'
      path: '/$runId'
      fullPath: '/benchmarks/$runId'
      preLoaderRoute: typeof BenchmarksRunIdRouteImport
      parentRoute: typeof BenchmarksRoute
    }
  }
}

interface BenchmarksRouteChildren {
  BenchmarksRunIdRoute: typeof BenchmarksRunIdRoute
}

const BenchmarksRouteChildren: BenchmarksRouteChildren = {
  BenchmarksRunIdRoute: BenchmarksRunIdRoute,
}

const BenchmarksRouteWithChildren = BenchmarksRoute._addFileChildren(
  BenchmarksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenchmarksRoute: BenchmarksRouteWithChildren,
  HistoryRoute: HistoryRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  ScanIdRoute: ScanIdRoute,
  ScanNewRoute: ScanNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
